import type { Metadata } from 'next'
// import { Inter } from "next/font/google";
import './globals.css'

// const inter = Inter({ subsets: ["latin"] });
import Nav from '@/components/nav'
import { defaultRadius, defaultTheme } from '@/styles/themes/consts'
import { CSSProperties } from 'react'

export const metadata: Metadata = {
	title: 'Next Template',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			style={{ '--radius': `${defaultRadius}em` } as CSSProperties}
			data-theme={defaultTheme.toLowerCase()}
		>
			<body>
				<Nav />
				{children}
				<div className='dark:bg-[url(/images/bg-color.png)] dark:h-full dark:w-full opacity-90 fixed top-0 z-[-1]'></div>
			</body>
		</html>
	)
}
